#
# Copyright (c) 2017-2018 Bitprim Inc.
#
# This file is part of Bitprim.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

branches:
  only:
    - master
    # - /^v\d+\.\d+\.\d+$/
    - dev
    - /^release-\d+\.\d+\.\d+$/
    - /^release_\d+\.\d+\.\d+$/
    - /^hotfix-\d+\.\d+\.\d+$/
    - /^hotfix_\d+\.\d+\.\d+$/
    - /^feature-ci-.+$/
    - /^feature_ci_.+$/
    - /^feature-appveyor-.+$/
    - /^feature_appveyor_.+$/

build: false

environment:
    PYTHON: "C:\\Python27"
    PYTHON_VERSION: "2.7.8"
    PYTHON_ARCH: "32"
    CONAN_STABLE_BRANCH_PATTERN: "master$" #"release/*"

install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan --upgrade
  # - pip.exe install conan==1.0.0b5   #Fixed Beta version...
  - pip.exe install conan_package_tools
  - pip.exe install cpuid --upgrade
  - conan user # It creates the conan data directory

test_script:
  - git submodule init
  # - git submodule update --remote
  - git submodule update
  # - git fetch --unshallow
  - git fetch origin master:master

  - ps: |
      $a = python ci_utils/set_envvars_and_files.py
      Write-Host $a
      Invoke-Expression $a

  - python build.py


# test_script:
#   - for /f %%i in ('git describe') do set BITPRIM_BUILD_NUMBER=%%i
#   - echo "BITPRIM_BUILD_NUMBER   %BITPRIM_BUILD_NUMBER%"

#   - python .travis\update_version.py console\version.hpp "#define BITPRIM_NODE_EXE_VERSION " "#define BITPRIM_NODE_EXE_VERSION \"%BITPRIM_BUILD_NUMBER%\""
#   - type console\version.hpp

#   - python build.py


for:
  -
    branches:
      only:
        - /(dev|feature).*/    # Just development branches
    environment:
      matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15
          BITPRIM_CI_CURRENCY: BCH
          VS150COMNTOOLS: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\Common7\\Tools\\"
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15
          BITPRIM_CI_CURRENCY: BTC
          VS150COMNTOOLS: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\Common7\\Tools\\"
  -
    branches:
      only:
        - /^(release|hotfix).+$/    #Just releases
    environment:
      matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15
          BITPRIM_CI_CURRENCY: BCH
          VS150COMNTOOLS: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\Common7\\Tools\\"
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15
          BITPRIM_CI_CURRENCY: BTC
          VS150COMNTOOLS: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\Common7\\Tools\\"
        # - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
        #   CONAN_VISUAL_VERSIONS: 14
        #   BITPRIM_CI_CURRENCY: BCH
        # - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
        #   CONAN_VISUAL_VERSIONS: 14
        #   BITPRIM_CI_CURRENCY: BTC

  -
    branches:
      only:
        - master
    test_script:
      - echo "Stable packages are published in Release branches"
    install: 
      - echo "Stable packages are published in Release branches"


# MINGW_CONFIGURATIONS: "4.9@x86_64@seh@posix" 

# matrix:
#   fast_finish: true     # set this flag to immediately finish build once one of the jobs fails.

